#milestone-2
MxoDevops/Todo-list pull request #2
Opened 2022-07-22 16:53 UTC by MxoDevops

2022-07-22 17:59 UTC, ishimwezachee requested changes
Hi @MxoDevops , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-medium.gif"/>

## Highlights
Linters are passing 👍 
The project is running successfully 👍 
PR is well described 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 17:59 UTC, ishimwezachee commented on src/crud.js
> +});
- [ ]  Your delete function is not working, I am deleting either single task or the one which are checked, and none is being deleted.  when I reload the page the tasks are returned back.
- [ ]  When I check Item to completed,this property should be turned to `true`, but for now it not changed, while the task is checked, all the changes made in browser should be saved to local storage. 
![image](https://user-images.githubusercontent.com/43877689/180496554-13c13346-7054-4e80-8b0e-42ea476a0f4d.png)

2022-07-23 07:49 UTC, zainsadaqat requested changes
# Required Changes 🔁 
# Hello @MxoDevops  😃 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [ ] As requested by the previous Code Reviewer @ishimwezachee, When I check Item to completed, this property should be turned to true, but for now it has not changed, while the task is checked, all the changes made in the browser should be saved to local storage.
<img width="1152" alt="Screenshot 2022-07-23 at 12 49 43 PM" src="https://user-images.githubusercontent.com/83048208/180595963-b7fabac7-62d5-4ea7-a6d7-ad19896b8bf0.png">



_Check the comments under the review._


<img src="https://media0.giphy.com/media/QvMIzHw30MmMAqvOeo/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-23 09:45 UTC, BertrandConxy approved these changes
Hi @MxoDevops  ✋ , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💪 
- project works fine
- Nice UI
- no linter errors
- correct GitHub flow is used
- good PR description

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-23 09:46 UTC, merged